version: '3'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes: 
      - ./redis:/data
    restart: unless-stopped

  nextcloud:
    image: nextcloud:latest
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      - VIRTUAL_HOST=${COLLABORA_HOST}
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=${COLLABORA_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - RESOLVE_TO_PROXY_IP=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always
    links: 
      - db
      - redis
    volumes:
      - ./nextcloud-core:/var/www/html
      - ./nextcloud-apps:/var/www/html/custom_apps
      - ./nextcloud-data:/var/www/html/data
      - ./nextcloud-config:/var/www/html/config
    ports:
      - 81:80
    depends_on:
      - db
      - office
      - redis
  
  office:
    image: collabora/code:latest
    restart: always
    environment:
      - domain=office\\.cidogh\\.ca
      - username=${COLLABORA_USERNAME}
      - password=${COLLABORA_PASSWORD}
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
      - SLEEPFORDEBUGGER=0"
      - VIRTUAL_HOST=${COLLABORA_HOST}
      - VIRTUAL_PORT=9980
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=${COLLABORA_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - RESOLVE_TO_PROXY_IP=true
      - NETWORK_ACCESS=internal
    ports:
      - 9980:9980
    cap_add:
      - MKNOD
